const express = require("express")
const app = express()
app.use('/scripts.js', express.static('scripts/build/bundle.js'))
app.use('/engine.js', express.static('build/engine.js'))
app.use('/data.json', express.static('build/data.json'))
app.use('/fonts.json', express.static('build/fonts.json'))
app.use('/atlas.png', express.static('build/atlas.png'))
app.use(express.static('static'))
app.listen(80, '0.0.0.0', () => console.log('express up and running'))
