export const enum CONST {
	GRID_BASE = 120,
	FALLBACK_DELAY = 100,
	WALK_SPEED_SCALE = 100,
	WALK_BASE_SPEED = 25,
	WALK_DIRECTION_MODIFIER = 0.8,
	MAX_ANIMATION_STEPS = 128,
	MAX_ANIMATION_DELTA = 1000,
	STAGE_BASE_ZOOM = 2,
	CAMERA_SHAKE_DEFAULT_MAGNITUDE = 2,
	CAMERA_SHAKE_DEFAULT_SPEED = 2,
}
